#ifndef SWCJS_BINDING_H
#define SWCJS_BINDING_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct swcjs_ValueT swcjs_ValueT;

extern struct swcjs_ValueT *console;

struct swcjs_ValueT *swcjs_bin_eqeq(const struct swcjs_ValueT *lhs, const struct swcjs_ValueT *rhs);

struct swcjs_ValueT *swcjs_expr_member(struct swcjs_ValueT *val, const char *prop);

bool swcjs_if_condition(const struct swcjs_ValueT *con);

void swcjs_initialize(void);

struct swcjs_ValueT *swcjs_lit_bool(unsigned char v);

struct swcjs_ValueT *swcjs_lit_num(double v);

struct swcjs_ValueT *swcjs_lit_str(const char *s);

#endif /* SWCJS_BINDING_H */
